# Generated by Django 4.1.3 on 2022-12-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_serial_No', models.CharField(max_length=100)),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('date_purchased', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=264)),
                ('designation', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_staff', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_returned', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset', to='company.asset')),
                ('asset_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_taken', to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsCheckedOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked_out', models.BooleanField(default=False)),
                ('asset_checkedout_time', models.DateTimeField(auto_now_add=True)),
                ('asset_condition', models.CharField(choices=[('Good', 'Good'), ('Scratch', 'Scratch'), ('Broken', 'Broken')], default='Good', max_length=50)),
                ('asset_checked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked', to='company.employeeasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False)),
                ('asset_returned_time', models.DateTimeField(blank=True, null=True)),
                ('asset_returned_condition', models.CharField(choices=[('Good', 'Good'), ('Scratch', 'Scratch'), ('Broken', 'Broken')], default='Good', max_length=50)),
                ('asset_returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned', to='company.employeeasset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company'),
        ),
    ]
