# Generated by Django 4.1.3 on 2022-12-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='employee_user',
        ),
    ]
